### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by irostam** [deano2390/OpenFlappyBird#1]
What is this error about?
![screenshot 21](https://cloud.githubusercontent.com/assets/5684908/3635149/2872b028-0f60-11e4-97d2-6f93c053ab38.png)

**Comment by deano2390** [comment]
Use the android sdk manager to install the missing sdk versions, or change the project target to ones that you have, pretty sure there is no actual dependency on api level 15 or 20. Similar issue posted here: http://stackoverflow.com/questions/18930762/unable-to-resolve-target-android-18-error

**Comment by irostam** [comment]
<string name="app_id">1021847987218</string>
So what is this error for??

**Comment by deano2390** [comment]
See the red text in the console window? It's because your manifest is referencing a version of the android SDK that you do not have installed. Either change the target SDK or install the versions that are missing. The '1021847987218' error in the xml is not a real error, it will vanish when you resolve the SDK issue.
